### PR TITLE
add aws-region as a parameter

### PR DESCRIPTION
**Pull request by dszabome**

### CODE REVIEW

**Comment by cannikin** [comment]
Thanks for the contribution! Is this theoretical or have you tried this and it works okay?

**Comment by dszabome** [comment]
Yes, I tested it, works well.

**Comment by cannikin** [comment]
Sounds good, thanks!

**Comment by cannikin** [comment]
If you're still feeling generous you could update the README to include the region param in the command example. :)

**Comment by dszabome** [comment]
Sure, I added a new pull request.

**Pull request merged**
